---
apiVersion: v1
kind: Secret
metadata:
  name: git-auth
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: xxx
  password: xxx
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-auth
  annotations:
    tekton.dev/docker-0: https://registry.cn-huhehaote.aliyuncs.com
type: kubernetes.io/basic-auth
stringData:
  username: xxx
  password: xxx
