---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-utils
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-utils
rules:
  - apiGroups: [""]
    # secrets are only needed for Github/Gitlab interceptors
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  # Permissions to create resources in associated TriggerTemplates
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources", "taskruns"]
    verbs: ["create", "get", "list", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-utils
subjects:
  - kind: ServiceAccount
    name: tekton-utils
roleRef:
  kind: Role
  name: tekton-utils
  apiGroup: rbac.authorization.k8s.io